gText_Birch_Welcome_Custom::
# 1 "data/text/birch_speech_custom.pory"
	.string "...\n"
	.string "...\p"
	.string "...\n"
	.string "...\p$"

gText_Birch_Welcome_Choose_Gender_Custom::
# 8 "data/text/birch_speech_custom.pory"
	.string "... What was\n"
	.string "... I?$"

gText_Birch_Welcome_Choose_Name_Custom::
# 13 "data/text/birch_speech_custom.pory"
	.string "My name was...$"

gText_Birch_SoItsPlayer_Custom::
# 17 "data/text/birch_speech_custom.pory"
	.string "{PLAYER}{KUN}?$"
